
version: 2.1

jobs:
  build-and-deploy-staging:
    docker:
      - image: cimg/php:7.4-node
    steps:
      - checkout
      - run: composer install
      - run: composer dump-autoload
      - run: npm install
      - run: npm run build
      - add_ssh_keys:
          fingerprints:
            - "f3:2b:cf:8b:63:84:23:8f:ed:dc:2b:0a:28:77:f4:5a"
      - run: ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
      - run: sudo apt update
      - run: sudo apt install rsync
      - run:
          rsync -avzr --delete --delete-excluded --exclude-from='exclude-list.txt' -e "ssh -p $SSH_PORT" ./ $SSH_USER@$SSH_HOST:/staging4.puffininno.com/public_html/wp-content/themes/puffin-innovations

workflows:
  version: 2.1
  build_and_deploy_staging:
    jobs:
      - build-and-deploy-staging:
          filters:
            branches:
              only: staging
